### ISSUE TITLE
Error: Request aborted

### ISSUE THREAD

**Issue by joeyism** [scalabel/scalabel#263]
When I try to create a new Project on a remote server, I get this error

```
app:4428:2021-03-15_13-42-24 info: Found 0 projects
app:4428:2021-03-15_13-42-39 info: Requesting /postProject
Error: Request aborted
    at IncomingMessage.<anonymous> (/home/app/scalabel/node_modules/formidable/lib/incoming_form.js:122:19)
    at IncomingMessage.emit (events.js:314:20)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at abortIncoming (_http_server.js:533:9)
    at socketOnClose (_http_server.js:526:3)
    at Socket.emit (events.js:326:22)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at TCP.<anonymous> (net.js:675:12)
```
and the project doesn't get created. I've tried it several times and get the same result every time. What can I do to resolve this issue?

**Comment by jokober** [comment]
Hi, I have the same problem. Have you found a solution?

**Comment by jokober** [comment]
I actually managed to solve the issue. Instead of Firefox I tried to create the project using chromium. There I got alerts which I didn't get on firefox. The alert hinted that one of the uploaded files is not formatted correctly. It turned out that one '-' was missing in my attributes file ...
