### ISSUE TITLE
Ubuntu installation fails

### ISSUE THREAD

**Issue by emmbertelen** [scalabel/scalabel#289]
This is the error i get while running the setup_ubuntu.sh  :

```
[2021-04-27 10:18:24] Compiling source code
[2021-04-27 10:18:24] ================================
Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
 - options[0] misses the property 'patterns'. Should be:
   [non-empty string | object { from, to?, context?, globOptions?, filter?, transformAll?, toType?, force?, priority?, info?, transform?, transformPath?, noErrorOnMissing? }, ...] (should not have fewer than 1 item)
 - options[1] misses the property 'patterns'. Should be:
   [non-empty string | object { from, to?, context?, globOptions?, filter?, transformAll?, toType?, force?, priority?, info?, transform?, transformPath?, noErrorOnMissing? }, ...] (should not have fewer than 1 item)
 - options[2] misses the property 'patterns'. Should be:
   [non-empty string | object { from, to?, context?, globOptions?, filter?, transformAll?, toType?, force?, priority?, info?, transform?, transformPath?, noErrorOnMissing? }, ...] (should not have fewer than 1 item)
 - options[3] misses the property 'patterns'. Should be:
   [non-empty string | object { from, to?, context?, globOptions?, filter?, transformAll?, toType?, force?, priority?, info?, transform?, transformPath?, noErrorOnMissing? }, ...] (should not have fewer than 1 item)
ValidationError: Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
    at validate (/home/peter/3D_labeling/scalabel/node_modules/copy-webpack-plugin/node_modules/schema-utils/dist/validate.js:104:11)
    at new CopyPlugin (/home/peter/3D_labeling/scalabel/node_modules/copy-webpack-plugin/dist/index.js:38:31)
    at Object.<anonymous> (/home/peter/3D_labeling/scalabel/webpack.config.js:32:5)
    at Module._compile (/home/peter/3D_labeling/scalabel/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (/home/peter/3D_labeling/scalabel/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
```

 - OS: Ubuntu 20.04

Can anyone please help me with this?

**Comment by fyu** [comment]
What are your outputs of `npm -v copy-webpack-plugin` and `node -v`? The error is strange, since our CI are constantly testing the ubuntu setup: https://github.com/scalabel/scalabel/runs/2442430833
