### ISSUE TITLE
command python3 -m scalabel.vis.label reeor

### ISSUE THREAD

**Issue by jjjjjkkkk** [scalabel/scalabel#384]
![Screenshot from 2021-11-15 15-55-30](https://user-images.githubusercontent.com/39030589/141744344-a476fe3d-69a1-4248-a58f-48213ff56a8d.png)

**Comment by Timmy-485** [comment]
run right into this same issue, wondering if you found a work around it?

**Comment by jokober** [comment]
Hi, I got a similar issue but when converting the exported scalabel json to coco format:
```

/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'scalabel.label.to_coco' found in sys.modules after import of package 'scalabel.label', but prior to execution of 'scalabel.label.to_coco'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
[2021-12-20 14:46:40,826 to_coco.py:513 run] Loading Scalabel jsons...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/kubus/workspace/scalabel/scalabel/label/to_coco.py", line 548, in <module>
    run(parse_arguments())
  File "/home/kubus/workspace/scalabel/scalabel/label/to_coco.py", line 514, in run
    dataset = load(args.input, args.nproc)
  File "/home/kubus/workspace/scalabel/scalabel/label/io.py", line 105, in load
    config = Config(**cfg)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for Config
categories -> 0
  value is not a valid dict (type=type_error.dict)
categories -> 1
  value is not a valid dict (type=type_error.dict)`

```

**Comment by jokober** [comment]
I found a quick and dirty fix which is working for now. However probably maintainers should do a real fix.

The error was thrown in following lines:
https://github.com/scalabel/scalabel/blob/4a7c5d9fd836f18f6180f012445db1d9c8188be0/scalabel/label/io.py#L102-L104

To solve the issue I simply changed the type of the list of categories in the dict to a list of dict:
``` python
cfg["categories"] = [{"name": cat} for cat in cfg["categories"]]
```

I also had to add a new field "imageSize" as this was the next error popping up:
``` python
cfg["imageSize"] = {"width":3840, "height":2160}
```

So now the block of code looks like this:
``` python
    config = None
    if cfg is not None:
        cfg["imageSize"] = {"width":3840, "height":2160}
        cfg["categories"] = [{"name": cat} for cat in cfg["categories"]]
        config = Config(**cfg)
```
