### ISSUE TITLE
Can't convert from coco to Scalabel using from_coco.py

### ISSUE THREAD

**Issue by AliNaqvi110** [scalabel/scalabel#451]
Hi  I have a issue for converting coco label to scalabel
Traceback (most recent call last):
  File "from_coco.py", line 7, in <module>
    from typing import Dict, List, Optional, Tuple
  File "/content/scalabel/scalabel/label/typing.py", line 3, in <module>
    from typing import Any, Dict, List, Optional, Tuple, Union
ImportError: cannot import name 'Any' from 'typing' (/content/scalabel/scalabel/label/typing.py)

**Comment by tobiasfshr** [comment]
which python version are you using?

**Comment by AliNaqvi110** [comment]
Thanks for reply,  I have
Python 3.7.13

But the issue is he can't import these functions name 'Any' from typing.py.
And I also could'nt find these in typing.py

**Comment by AliNaqvi110** [comment]
Is there any other way I can convert coco labels to scalabel format

**Comment by fyu** [comment]
@AliNaqvi110 The script should work now. How did you use it in the command line?
