### ISSUE TITLE
Missing 'frameIndex' property in downloaded label json file -> to_coco fails

### ISSUE THREAD

**Issue by jokober** [scalabel/scalabel#478]
**Describe the bug**
When converting labels to coco I get following assertion error: 

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/fids/scalabel/scalabel/label/to_coco.py", line 541, in <module>
    run(parse_arguments())
  File "/home/fids/scalabel/scalabel/label/to_coco.py", line 533, in run
    coco = convert_func(frames, config)
  File "/home/fids/scalabel/scalabel/label/to_coco.py", line 287, in scalabel2coco_box_track
    frames_list = group_and_sort(frames)
  File "/home/fids/scalabel/scalabel/label/io.py", line 124, in group_and_sort
    assert frame.frameIndex is not None
AssertionError
```
I checked the exported label json file and there is no 'frameIndex' property.  

**To Reproduce**
1. I downloaded the labels from my scalabel instance using the 'Download Labels' button
2. Afterwards I ran the to_coco like this: 
`python3 -m scalabel.label.to_coco --input /media/data/scalabel_work_dir/scalabel/dataset_export_2022-09-16_13-40-59.json -o /mnt/fdata/ -m det`
5. See error

**Expected behavior**

**Desktop (please complete the following information):**
Pop!OS 22.04
Scalabel Version 0.3 as well as current master

**Comment by jokober** [comment]
Sorry for pushing this issue a bit. For us it is crucial to get the labels out of scalabel including tracking data. Are there plans fix this issue any time soon?

**Comment by fyu** [comment]
@jokober can you post your image list for creating the labeling tasks?

**Comment by thomasehuang** [comment]
I pushed a fix to this PR #485, can you check if it addresses your issue? `frameIndex` represents the index of the corresponding image, which can be used to determined the ordering of the images in a video. Without it, we assume the given order is the correct order.

**Comment by jokober** [comment]
> @jokober can you post your image list for creating the labeling tasks?

Here is an extract of the image list
``
 [
    {
      "name": "MOT-1654349058_zoex_1600166_1600619/000001.jpg",
      "url": "localhost:8686/items/MOT-1654349058_zoex_1600166_1600619/img1/000001.jpg",
      "videoName": "MOT-1654349058_zoex_1600166_1600619",
      "intrinsics": null,
      "extrinsics": null,
      "attributes": null,
      "timestamp": null,
      "frameIndex": 0,
      "size": null,
      "labels": []
    },
    {
      "name": "MOT-1654349058_zoex_1600166_1600619/000002.jpg",
      "url": "localhost:8686/items/MOT-1654349058_zoex_1600166_1600619/img1/000002.jpg",
      "videoName": "MOT-1654349058_zoex_1600166_1600619",
      "intrinsics": null,
      "extrinsics": null,
      "attributes": null,
      "timestamp": null,
      "frameIndex": 1,
      "size": null,
      "labels": []
    },
    {
      "name": "MOT-1654349058_zoex_1600166_1600619/000003.jpg",
      "url": "localhost:8686/items/MOT-1654349058_zoex_1600166_1600619/img1/000003.jpg",
      "videoName": "MOT-1654349058_zoex_1600166_1600619",
      "intrinsics": null,
      "extrinsics": null,
      "attributes": null,
      "timestamp": null,
      "frameIndex": 2,
      "size": null,
      "labels": []
    },
]
``
