### ISSUE TITLE
Errors about converting SHIFT labels to COCO format

### ISSUE THREAD

**Issue by VictorYrotciV** [scalabel/scalabel#515]
Hi there,

I'm trying to convert SHIFT labels to COCO format for my own experiment settings of 2D Object Detection task. So I manually downloaded SHIFT annotation file of 1fps for example https://dl.cv.ethz.ch/shift/discrete/images/train/front/det_2d.json. After downloading and setting up scalabel, to convert det_2d.json to coco fromat json, I ran to_coco.py but it occured an error:
```
[2023-06-08 20:27:57,534 to_coco.py:516 run] Loading Scalabel jsons...
Traceback (most recent call last):
  File "/home/victory/workspace/scalabel/scalabel/label/to_coco.py", line 551, in <module>
    run(parse_arguments())
  File "/home/victory/workspace/scalabel/scalabel/label/to_coco.py", line 517, in run
    dataset = load(args.input, args.nproc)
  File "/home/victory/workspace/scalabel/scalabel/label/io.py", line 115, in load
    config = Config(**cfg)
  File "/home/yhz/anaconda3/lib/python3.9/site-packages/pydantic-2.0b2-py3.9.egg/pydantic/main.py", line 138, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 14 validation errors for Config
attributes
  Field required [type=missing, input_value={'imageSize': {'width': 1...}, {'name': 'bicycle'}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/0.38.0/v/missing
categories.0.subcategories
  Field required [type=missing, input_value={'name': 'pedestrian'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/0.38.0/v/missing
categories.0.color
  Field required [type=missing, input_value={'name': 'pedestrian'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/0.38.0/v/missing
categories.1.subcategories
  Field required [type=missing, input_value={'name': 'car'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/0.38.0/v/missing
categories.1.color
  Field required [type=missing, input_value={'name': 'car'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/0.38.0/v/missing
categories.2.subcategories
  Field required [type=missing, input_value={'name': 'truck'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/0.38.0/v/missing
categories.2.color
  Field required [type=missing, input_value={'name': 'truck'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/0.38.0/v/missing
categories.3.subcategories
  Field required [type=missing, input_value={'name': 'bus'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/0.38.0/v/missing
categories.3.color
  Field required [type=missing, input_value={'name': 'bus'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/0.38.0/v/missing
categories.4.subcategories
  Field required [type=missing, input_value={'name': 'motorcycle'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/0.38.0/v/missing
categories.4.color
  Field required [type=missing, input_value={'name': 'motorcycle'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/0.38.0/v/missing
categories.5.subcategories
  Field required [type=missing, input_value={'name': 'bicycle'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/0.38.0/v/missing
categories.5.color
  Field required [type=missing, input_value={'name': 'bicycle'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/0.38.0/v/missing
poseSigmas
  Field required [type=missing, input_value={'imageSize': {'width': 1...}, {'name': 'bicycle'}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/0.38.0/v/missing
```

I'm not familiar with pydantic. Do you have ideas about how to fix this and convert SHIFT labels to COCO format?

**Comment by thomasehuang** [comment]
This is probably due to a new version of pydantic that came out recently. Can you try `pip install -U pydantic==1.9.1` to downgrade it?

**Comment by VictorYrotciV** [comment]
This worked. Thx!

> This is probably due to a new version of pydantic that came out recently. Can you try `pip install -U pydantic==1.9.1` to downgrade it?
